esp-rs/esp-idf-hal

src/delay.rs, src/gpio.rs, src/i2c.rs
These changes were all that was required to make this work with OneWire via the `one_wire_bus` crate; all GPIO appears to work fine thereafter.
- Implement `DelayMs` for the `Ets` delay provider
- Implement `OutputPin` as well as the existing `InputPin` for `Gpioxx<InputOutput>` to satisfy the `T: InputPin + OutputPin` constraint
- Use the same `Error` type for both `InputPin` and `OutputPin`. I'm conflicted about this last one; I can see why `InputPin` was considered `Infallible`, and perhaps this should be raised against the driver crate, but on the other hand when using a pin in `InputOutput` mode it makes sense not to have two Error types.
=> Updates for compatibility with OneWire

src/gpio.rs
I noticed that a number of GPIO for the ESP32-S2 and ESP32-S3 had incorrect modes being specified. I have gone through both datasheets and (hopefully) corrected these issues.
=> Correct available modes for various GPIO on ESP32-S2/S3

src/gpio.rs, src/i2c.rs, src/serial.rs, src/spi.rs
The new GpioPin type is generic over its direction (Input or Output) and captures the pin number in a member variable.
It is useful for situations where concrete types cause errors, e.g. collecting multiple pins in an array. At the same time the new type is conform with the current API for peripherals.
This is an implementation of #15.
=> Add a generic `GpioPin` type for downgrading

src/gpio.rs
Since we are not reliably able to read the output state with the existing implementation, I've just dropped down a level and read the `GPIO_OUT_REG` register directly. This is a bit ugly, but the `StatefulOutputPin` and `ToggleableOutputPin` trait implementations are now working as expected. If there is a function in `esp-idf-sys` which will do this please let me know, but I did not see one.
This has been tested on the ESP32, ESP32-C3, and ESP32-S2. Just to note, I did try testing the ESP32-S3 as well but encountered an error originating from `esp-idf-sys` saying that PIO did not have a matching definition for the ESP32-S3.
Fixes #17
=> Apply fix to read output state of a GPIO successfully

src/gpio.rs
This should fix #9 as far as I can tell. Did some quick testing on various pins for the ESP32 and ESP32-C3, everything seems happy. ~~I'm unfortunately unable to use the `reset` function in the various `into_` functions because it takes `&mut self`.~~
=> Reset GPIO pins prior to setting them as inputs or outputs

README.md, src/gpio.rs
- Adds (all?) previously missing GPIO pins
- Set all of the ESP32-C3's GPIO's as `NOTOUCH`, as it does not have a touch controller
- Mention in the `README` which pins are not recommended for use
Closes #8
=> Add missing GPIO pins

src/i2c.rs, src/serial.rs, src/spi.rs
After updating Rust nightly (to `rustc 1.59.0-nightly (7abab1efb 2021-12-17)`) a new lint rule was added to clippy, which caused some lint errors. This fixes them.
=> Apply fixes for new lint added in most recent nightly version of clippy

src/delay.rs
I needed this in order to use a [DHT22 sensor driver](https://github.com/michaelbeaumont/dht-sensor) and that requires a DelayUs<u8> implementing type.
=>  Implement DelayUs<u8> and DelayMs<u8> for delay::Ets

src/cpu.rs, src/lib.rs, src/ulp/sys/cpu.rs
According to https://github.com/rust-lang/rust/issues/70173#issuecomment-1012092455, `asm!` got stabilized in nightly and `llvm_asm!`
Migrating to `asm!` makes this crate compile again with nightly 2022-01-17 for me. Thank you @jessebraham for pointing me to the issue above!
=> Migrate llvm_asm! to asm!

src/cpu.rs
This avoids a compiler warning on single-core targets which do not perform an actual check. This fixes #36. Sorry that i missed this in the first place.
=> Conditionally import asm! macro at src/cpu.rs

src/prelude.rs
I'm using this crate in a project and needed some of the `embedded-hal` traits in scope. I didn't otherwise require the crate, so it seemed a little silly to add it as a dependency. Instead, we can re-export the traits in the prelude.
I believe this covers everything that has been implemented so far.
=> Re-export `embedded-hal` traits in prelude

.cargo/config.toml, .github/configs/sdkconfig.defaults, .github/workflows/ci.yml, Cargo.toml, README.md, build.rs, examples/ledc-simple.rs, examples/ledc-threads.rs, src/ledc.rs, src/lib.rs, src/peripherals.rs
- This PR adds a basic driver for the LEDC peripheral
- Timers and output channels can be freely combined
- Provides an implementation of `embedded-hal`'s `PwmPin` trait
- Allows setting PWM frequency duty-cycle resolution, and duty-cycle
- More sophisticated features like fading are not implemented yet
- Batteries in form of two examples are included
- This PR also adds default configuration which allows to conveniently built and run them with an already released `cargo-espflash`
- ESP IDF SDK configuration
- (Nightly) build flags
- An increased main task stack size for running the examples
=> Add basic driver for LEDC

src/gpio.rs
Hi !
Here is a first proposal for a GPIO interrupt handler subscription.
1. I chose to implement a new state rather than subtyping `Input` because I am not sure that a Pin used for interrupt would be used for something else.
2. I did not implemented it for `InputOutput` because when testing interrupt on Pin configured this way I was not able to get any interrupt, so I am not sure that it's possible with `esp-idf`.
3. I keep the PinNotifySubscription in a static mut array `IRQ_HANDLERS` and did not guard access to it with a Mutex because I guess that needing to own the pin makes it thread safe as long as we respect the current state.
4. It's not possible to register a new handler if you did not unsubscribed the older before.
5. I need to init the array with the full value list, because …
=> add interrupt subscription

src/i2c.rs
This PR provides an implementation for `I2c::transaction`.
~I didn't add `i2c_master_write` and `i2c_master_read` to the `CommandLink` implementation since that would require lifetime annotations and I'm can't be bothered to sprinkle them everywhere.~
=> Support I2C transactions

src/i2c.rs
The main motivation for this PR is to allow me to implement ack polling.
I've split it up into three commits for easy review.
1. Just small refactor to use safe `CommandLink` methods added in #59 .
2. Skip command if buffer is empty. The esp-idf driver complains if you call `i2c_master_write` and `i2c_master_read` with an empty buffer.
3. When the command_link is submitted and `ESP_FAIL` is returned, it means the slave didn't ack. I've simply made a change here to make this more visible in a generic driver.
I'm working with an EEPROM, where after sending a write command to it, it stops responding to it's slave address until it's done writing. To check if the device is accepting commands again, I have to call `Master::write(addr, &[])` until it doesn't fail with `ErrorKind::NoAcknowledge`. …
=> Improve I2C errors

Cargo.toml, examples/spi_loopback.rs, src/adc.rs, src/gpio.rs, src/hall.rs, src/spi.rs
See https://github.com/rust-embedded/embedded-hal/releases/tag/v1.0.0-alpha.8
Some adc traits were removed.
GitHub diff looks a bit weird so maybe use the Side by side viewer.
In the meantime, I'm going to test this on my SPI device.
=> Migrate to e-hal 1.0.0-alpha.8

src/serial.rs
Here
```rust
let uart_config = uart_config_t {
baud_rate: config.baudrate.0 as i32,
data_bits: config.data_bits.into(),
parity: config.parity.into(),
stop_bits: config.stop_bits.into(),
flow_ctrl: config.flow_control.into(),
..Default::default()
};
```
..Default::default() sets `rx_flow_ctrl_thresh` to `0` which is not desirable, because then `RTS` line is asserted after every received byte. ESP32 has ~128 byte RX FIFO, so it makes sense to be around this large. Most of the ESP32 [examples](https://docs.espressif.com/projects/esp-idf/en/release-v3.3/api-reference/peripherals/uart.html) are using `122` for `rx_flow_ctrl_thresh`.
This is how it looks like when it is `0` (RTS is asserted for ~1ms after every received byte):
With `122` it looks much better:
=> serial: set rx_flow_ctrl_thresh to 122

src/spi.rs
In #61, I provided new implementations of the SPI transfer methods for e-hal 1.0's SPI traits. (I've successfully used them to drive an E-Ink display and SD card).
This PR is to also make use of these methods in e-hal 0.2's SPI traits.
Main advantage of the new methods is that no temporary buffers are created, which is great for DMA.
=> Reuse new SPI transfer methods

examples/spi_loopback.rs
Fix SDI and SDO been mixed up in the example.
Update to new names as per:
https://www.oshwa.org/a-resolution-to-redefine-spi-signal-names
=> Fix SPI loopback exmaple -- mixed up SDI and SDO

src/spi.rs
Add the possibility to configure:
- SPI_DEVICE_NO_DUMMY unlocking 80Mhz for write only spi transfers. This alone allowed me to improve a full screen (240*240 pixels) from ~148ms down to ~95ms
- `max_transfer_size` and `dma_channels` which can be used to improve even more the transfer by minimizing the number of transfers and use the DMA capabilities of the idf implementation of spi
Also, the goal is to address #64
=> Add spi bus and device options

src/spi.rs
Following the previous PRs, here is a proposition to enable configuration of `max_transfer_size` and `Dma` activation.
However, I am not satisfied with the content, because as said before if we use `transfer_size > 64` without Dma it panics :\
Do you think `max_transfer_size` should be silently lowered when Dma is not used ?
Any idea of another to notify the user he's doing something wrong ?
Would some documentation on the method be enough ?
=> Add possibility to setup Dma and max_transfer_size

src/i2c.rs
ESP-IDF itself will set both pins as `INPUT_OUTPUT_OD`, so we should ensure that the pins are capable of that.
The reason behind that is probably because both the master and slave actually need to be able to read and write the clock line.  I2C has a thing called "clock stretching" where a slave device will hold the clock line low to indicate that it needs a little time to complete the master's request.  So in that case the slave needs output as well as input, and the master needs input as well as output.
=> i2c: SCL pin should be both output and input

src/i2c.rs
Of course I notice this right after you merge it...
=> i2c: fix double InputPin typo

examples/rmt_morse_code.rs, examples/rmt_musical_buzzer.rs
Noticed during #96 that some of the examples does not compile for ESP32 and ESP32-C2. Not 100% sure if these changes will have bad consequences
=> Make RMT examples compile for ESP32 and ESP32-C2

.github/workflows/ci.yml, .github/workflows/publish-dry-run.yml, .github/workflows/publish.yml, src/hall.rs
From what I understand CI is currently only run for the ESP32-C3. This PR adds a github workflow for the ESP32. I believe this could be useful since some code is not active when building for the ESP32-C3.
Suggestions are welcome. [Here](https://github.com/usbalbin/esp-idf-hal/runs/7157420054?check_suite_focus=true) is the result of the run.
=> Add CI for ESP

src/mutex.rs
This was a tricky one to track down! We started seeing reports of issues using WiFi on the new esp rust board (which uses usb-serial-jtag, importantly). I initially started looking at WiFi initialization differences as the esp-idf examples worked fine. Eventually though, I tracked the issue down to the wait for connect condvar timing out instantly. 
Using the rust-std-demo example, here was what was happening:
The rust code calls wait with a time-out duration (20 seconds) on the pthread condvar, the condvar being the wifi status. However, when resetting with USB serial jtag this timeout triggers immediately.
I tracked the down to the failure point being this piece of code in esp-idf:
```c
if (timercmp(&abs_time, &cur_time, <)) {
/* As per the pthread spec, if the time has already
* …
```
=> make condvar wait use absolute time

src/delay.rs
This prevents a panic when trying to "infinite"-delay with a value of `u32::MAX`. (yes, this does happen in real life here and there.)
=> FreeRtos.delay_ms_internal: use saturating_add for round-up-divide calc

src/rmt.rs
Adds `rmt::Transmit::start_iter` and `rmt::Transmit::start_iter_blocking` that allow to
transmit items generated on-the-fly by a rust iterator. This is done by using the
`translator` feature of the rmt peripheral.
See the documentation in the code for how it works exactly.
=> rmt: Add support for transmitting rust iterators

src/adc.rs
As per https://docs.espressif.com/projects/esp-idf/en/latest/esp32/migration-guides/release-5.x/peripherals.html#adc, the hall sensor is now unsupported
=> V5 ESP32 Hall Sensor unsupported

src/lib.rs, src/reset_reason.rs
Primarily useful because this gives me a readable `Debug` impl for the reset reason. There may be a way to have `esp-idf-sys` generate some more reasonable code as an alternative.
Invoking this looks a bit funny because the module name and the type name are similar:
```
let rr = esp_idf_hal::reset_reason::ResetReason::get()
```
Open to changing it so it looks different, if others have ideas about how to better form this.
=> reset_reason: wrap `esp_reset_reason()`

src/peripherals.rs, src/uart.rs
The esp32-s3 ([datasheet](https://www.espressif.com/sites/default/files/documentation/esp32-s3_datasheet_en.pdf)) has three UARTs, so `uart2` should be exposed in the HAL.
=> Implement uart2 for esp32-s3.

Cargo.toml, examples/ledc-simple.rs, examples/rmt_morse_code.rs, examples/rmt_musical_buzzer.rs, examples/rmt_neopixel.rs, examples/spi_loopback.rs, src/can.rs, src/delay.rs, src/gpio.rs, src/i2c.rs, src/ledc.rs, src/riscv_ulp_hal/delay.rs, src/spi.rs, src/uart.rs
See https://github.com/rust-embedded/embedded-hal/releases/tag/v1.0.0-alpha.9
`embedded-can` and `embedded-hal-nb` were split out of the main crate
=> Migrate to `embedded-hal` 1.0.0-alpha.9

src/ledc.rs
`esp-idf-hal` lacks hpoint control, which makes non-trivial LEDC implementations awkward.
This PR adds the option.
=> Add HPoint control to LEDC

src/gpio.rs
Two separate docstring fixes, please see commit messages.
=> Fix GPIO docstrings

src/spi.rs
By using a config option to busmaster builder
=> Add half duplex and 3wire mode support to SPI

src/can.rs
It would be nice if we could set custom CAN timings. I'm working on a project which uses a non-standard one.
This change requires deriving PartialEq and Eq for ```twai_timing_config_t```. I'll make an additional pull request for esp-idf-sys to fix the compilation issue.
=> Add can custom timing

.github/workflows/ci.yml
Update CI to also run for IDF 5.0
=> Ci for idf 5.0

src/timer.rs
Fixes #187 
I did not expose setters or getters for the `auto_reload` value after creation. Having those would maybe be nicer, but I did not find any `*_in_isr` version for `set_auto_reload` and no non-in_isr version of `get_auto_reload`. So I ignored that for now. Having this in `Config` at least allows me to do what I want to do with the timers.
=> Add auto_reload functionality to timers

src/spi.rs
Fixes #163
`SpiBusDriver` is a struct to be used when one needs exclusive access to the SPI bus without interference from other devices.
I renamed the existing `SpiBusDriver` to `SpiSharedBusDriver` since it's a better fitting name IMO. It's not really a public type since users should be going through the e-hal trait or using type inference.
The `Device` struct was introduced to make Rust drop the `Lock` before calling `spi_bus_remove_device()`. Another way to achieve this is with `ManuallyDrop` but that requires `unsafe`.
=> Implement exclusive SPI Bus

src/spi.rs
Fixes #191 by moving the bit read time so the sender device can setup the data correct.
=> Add input_delay_ns to config struct

src/can.rs
It would be nice if we could set a custom tx/rx queues length for CAN. In some cases, the default size of 5 is not enough.
=> Add queue length to CAN config

src/spi.rs
I wanted to submit a pull request to change the usage of `usize` to `NonZeroUsize` in the DMA channel enum. This fixes #201.
This is a breaking change, as `NonZeroUsize` is a wrapper around `usize` that ensures the value is non-zero. This change is being made to prevent panic when a zero value is used. Let me know if you have any questions or concerns.
Thank you for considering this change!
=> Fix issue #201: Use `NonZeroUsize` to specify DMA transfer size

examples/rmt_neopixel.rs
Bits were sent reversed, which worked for 0xff but not at smaller values to dim the LED. Also added rainbow example using a hsv function.
=> Correct endianness of RMT signal in neopixel example

.github/workflows/ci.yml
- Avoid failing fast in the matrix
- Define `GITHUB_TOKEN`, see https://github.com/esp-rs/xtensa-toolchain#environment
- Remove `libncurses5` dependency
- Upgrade `xtensa-toolchain` version
=> Update `xtensa-toolchain` action

src/i2c.rs
Some i2c devices require a longer timeout to allow clock stretching.  This PR adds an optional `timeout` to the i2c master config.
=> i2c: allow setting a timeout to accommodate devices with longer clock stretching

src/can.rs
With this PR, I’d like to add the possibility to specify different operation modes and alert configuration for `CanDriver`.
=> Alerts and modes support for TWAI

src/ledc.rs
Hi there,
This proposed minor addition gives the ability to set the frequency of an LedcTimerDriver after it has been created by calling the esp-idf function [ledc_set_freq](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/peripherals/ledc.html#_CPPv413ledc_set_freq11ledc_mode_t12ledc_timer_t8uint32_t).  I've found it quite helpful for a quick and dirty PWM controller for motor drivers and such. 
I wasn't sure what to do about the frequency of the TimerConfig object since the LedcTimerDriver seems to be where you control the timer but I am open to suggestions 😊. It has been tested on an ESP32-S3
Please let me know if you need anything else before reviewing the request.
=> Improvement: Set LedcTimerDriver frequency

Cargo.toml, examples/spi_loopback.rs, src/delay/general_purpose.rs, src/delay/mod.rs, src/gpio.rs, src/i2c.rs, src/ledc.rs, src/lib.rs, src/riscv_ulp_hal/delay.rs, src/spi.rs
This PR is in preparation of [this PR](https://github.com/rust-embedded/embedded-hal/pull/443) 
It will also resolve issue rust-lang/cargo#99  and will supersede PR rust-lang/cargo#223  & PR rust-lang/cargo#138 
The linked embedded-hal PR also already implements changes from current master embedded-hal::delay & embedded-hal::digital, therefore this PR made also changes to gpio.rs and mod.rs to make it work.
Edit1: also incorporate the i2c ehal master changes merged https://github.com/rust-embedded/embedded-hal/pull/440
Edit2: also impl pwm traits inside ledc.rs
=> Embedded-Hal PR - incoorparate e-hal master changes in spi / i2c / gpio / delay 

src/reset.rs
See https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/system/sleep_modes.html#external-wakeup-ext0 for more information on ext0 vs ext1
Resolves #256
=> Add support for WakeupReason from Ext0 events

src/lib.rs, src/rom/crc.rs, src/rom/mod.rs
This is the safe CRC abstraction over the newly merged esp-rs/esp-idf-sys@4ffb8838c8bb9e76c43ca021fdb9b5050340d036
I created the `rom` module to put commonly available ROM libraries, such as CRC. MD5 could be next. Since these libraries rely on the bindings provided by esp-idf-sys but are only on ESP32 chips they belong here in esp-idf-hal and not esp-idf-svc.
Test code is below or at [my repository](https://github.com/jordanhalase/test-esp-idf-hal-crc/blob/master/src/main.rs)
```Rust
use esp_idf_sys as _; // For binstart
use esp_idf_hal::rom::crc;
fn main() {
esp_idf_sys::link_patches();
let data = "123456789";
loop {
let crc_hdlc = crc::crc32_le(!0xffffffff, data.as_ref());
let crc_bzip2 = crc::crc32_be(!0xffffffff, data.as_ref());
let crc_mpeg2 = !crc::crc32_be(!0xffffffff, …
```
=> Add safe abstractions to CRC functions in ESP ROM

src/can.rs
By default the [single shot](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/peripherals/twai.html#message-fields-and-flags) flag is set for all CAN frames. Therefore the esp will only try to send each frame once. This is no problem if there is only ever one device sending messages on the bus. But it can lead to "dropped" frames with multiple transmitting devices, as a failed arbitration (i.e. another device sends a frame with a higher priority id at the same time) is not that uncommon. There might be situations where single shot frames can be useful; but in my opinion the default behaviour should be that retransmission is tried automatically.
This pull request simply removes the lines setting the single shot flag in the frame constructors.
Maybe we should add …
=> Try retransmission of CAN frames by default

src/rom/crc.rs
Fixed some typos in the docs. No code change.
=> Fix typos in rom::crc docs

examples/rmt_neopixel.rs
Refactoring of the `rmt_neopixel.rs` example:
* HSV conversion as an associated function, `Rgb::from_hsv()`
* Add `Rgb::new()`
* Implement `From<Rgb>` for `u32`
* Use cyclic iterator to eliminate counter when looping over hue values
* Replace `if-else` with pattern matching
=> Refactor Rgb struct

examples/pcnt_i64_encoder.rs
This fixes a clippy issue from rust-analyzer that's been sitting in VSCode's problems pane for a while.
=> pconfig does not need to be mut.

src/reset.rs
Extend the WakeupReason::ULP to match both COCPU and ULP (fsm) wakeups.
=> Map ULP wakeup to WakeupReason::ULP

examples/i2c_master_slave.rs
Adds an example that demonstrate both i2c master and slave, and does a test that run both on the same device, related to https://github.com/esp-rs/esp-idf-hal/issues/29
The test does three things:
1. Simple master write, master writes 8 bytes and print out what slave receives
2. Simple master read, master read 8 bytes and print out.
3. Read/write register, write a value to a register addr and read it back.
Tested on ESP32 only, but should also work on ESP32-S2/S3 so if anybody can test those that would be nice. ESP32-C2/C3 wont work since they only have one I2C.
If master tries to read a register with `write_read()`, then the slave will not respond correctly, it required separate write and red commands. I will try to improve on this, but it might need changes to i2c.rs 
The code from this …
=> adds example for i2c between master and slave I2C on same device

examples/timer_notify.rs
A simple example how to notify a task from a hardware timer ISR.
I think using the EspTimer is more useful, but people like to use the Hardware timer directly so that's why i made the example. 
CI will tell me if that's is working in newer IDF versions. Might need to rework the API for IDF 5 since they axed the api and now have it called general purpose timer.
=> 🚸 add simple timer example with task notify

src/can.rs
This PR adds support for [ESP32 TWAI Dual Filter Mode](https://docs.espressif.com/projects/esp-idf/en/latest/esp32/api-reference/peripherals/twai.html#acceptance-filter).
Tested on Xtensa based ESP32.
=> can: add dual filter support

src/spi.rs
embedded-hal got rid of these in the last release and users can easily use the `transaction` APIs instead.
=> Remove old e-hal methods SpiDeviceDriver

examples/adc_oneshot.rs, src/adc.rs
Implementation of the esp-idf v5 adc oneshot driver.
It would be nice to somehow replicate two C #define's info cfg's from esp-idf-sys so that we don't have to replicate logic determining if curve fitting and/or line fitting are suported based on version and cpu type:
- ADC_CALI_SCHEME_CURVE_FITTING_SUPPORTED
- ADC_CALI_SCHEME_LINE_FITTING_SUPPORTED
=> Adc oneshot driver

src/adc.rs, src/lib.rs, src/peripherals.rs
Fixes https://github.com/esp-rs/esp-idf-hal/issues/282.
ESP32C2 doesn't have an I2S peripheral. This is fixed by adding `esp_idf_soc_i2s_supported` cfg checks in various places.
ESP32C2's ADC perhiperhal doesn't have a continuous mode. Alas, ESP-IDF doesn't expose a flag for this, so we have to add a few `not(esp32c2)` checks in places.
=> Fix building for ESP32C2.

src/task.rs
I use NimBLE BLE stack.
In NimBLE library, a log structure is defined.  Therefore, `esp_idf_sys::log` is defined in esp_idf_sys.
(see: https://github.com/espressif/esp-nimble/blob/f8f02740acdf4d302d5c2f91ee2e34444d405671/porting/nimble/include/log/log.h#L39)
In task.rs, the log crate and sys_idf_sys::log are ambiguous and the following error occurs.
I changed to use the log crate explicitly.
```
error[E0659]: `log` is ambiguous
--> /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/esp-idf-hal-0.42.0/src/task.rs:232:5
|
232 |     log::trace!("block_on(): started");
|     ^^^ ambiguous name
|
= note: ambiguous because of a conflict between a name from a glob import and an outer scope during import or macro resolution
= note: `log` could refer to a crate passed with …
```
=> Fix ambiguous name error

CHANGELOG.md, src/timer.rs
On all devices that only use 2Timers / 1 group the current logic will wrongly index into the the 
`static mut ISR_HANDLERS: [Option<Box<dyn FnMut() + Send + 'static>>; 2] = [None, None];` array.
The old calculation produces 2 for group 1 index 0 ....
=> 🐛 fix wrong array indexing logic

src/spi.rs
I was unable to setup my m5stack core2 using an `ili9342c_rgb565` display where spi is on gpio38.
After a chat on matrix I made this change which worked.
=> Remove OutputPin requirement from SPI sdi pin

src/rmt.rs
When using `VariableLengthSignal`, going through the `set_{level,duration}{0,1}` methods for every symbol was too slow compared to straight copying a `rmt_item32_t` that was pre-made from Pulses.
This PR enables doing that without making a new custom implementation of Signal.
=> rmt: Allow working with raw rmt_item32_t for efficiency

src/timer.rs
=> Improve TimerDriver Documentation

src/adc.rs
NOTIFIER is not defined with esp_idf_adc_continuous_isr_iram_safe
=> fix: compile with esp_idf_adc_continuous_isr_iram_safe

src/uart.rs
On an esp32c6 with idf 5.1.1 (devkitC, although I doubt that matters), I could not for the life of me get the uart example to work.  Eventually I figured out that, at least in my particular setup, the default clock for the UART is the PLL_F80M clock... which must not have existed in earlier IDFs (or maybe it's particular to the esp32c6? Not sure, but it doesn't really matter).
This PR simply adds support in for the UART_SCLK_PLL_F80M clock source, since without this I couldn't get past a panic from creating the default uart config.
=> support uart that defaults to PLL_F80M

Cargo.toml
Version change: "1" -> "1.1"
`src/uart.rs` uses `EnumSet::EMPTY` for a `const fn`. `EnumSet::EMPTY` is not available in 1.0.0, but first introduced in 1.1.
=> Update enumset to 1.1

Cargo.toml
This should provide a slightly user-friendlier error message in the case that a user enables a different `restore-state` in `critical-section`.
Right now it's possible to e.g. enable the `std` feature on `critical-section`; `cargo` will not complain but `rustc` will complain about the return types of the `CriticalSection::enter` implementation.
=> Use `restore-state-none` feature in optional dependency `critical-section`

CHANGELOG.md, src/gpio.rs
=> don't touch pullups on reset while init PinDriver

examples/rmt_musical_buzzer.rs, src/rmt.rs
First, I introduce a newtype in the RMT module to remove the exposure of `rmt_item32_t` in the interface.
Then, I fix the `rmt_musical_buzzer` example to work on ESP32 (and maybe others) which is not supported by the ESP-IDF repo example. In the process, the example has now become a nascent 1-bit synthesizer.
=> RMT symbols and musical buzzer example bugfix for ESP32

src/delay.rs
This change adjusts some time conversions to include less error and also round up for delay.
As discussed in #367 it's typically desired to round delay times up instead of down, because a delay usually waits for a thing (e.g. hardware) to finish. If we would round down, it is more likely to cause ill effects than rounding up. The user code usually expects delaying a bit more.
In case of the coarse timer the "waiting a bit more" may be fairly large. But if the user code uses a coarse timer for small delays it's a problem in the user code.
This change also converts a couple of 'as' conversions to 'into()' calls.
RFC1: What you you think about removing the constant TICK_PERIOD_MS? It's not used internally anymore, because it might include an error that will get large in multiplications. …
=> Improve delay/timer errors and rounding calculations

src/delay.rs
This PR does the following changes:
* TickType: Make all functions const. That way times/ticks can be constructed const/static or in other const contexts.
* Inline all trivial functions.
* Remove the raw unsafe ets_delay_us() export. It's not really useful. The program can just use the safe Ets::delay_us() instead.
* Add more documentation and fix some wording in the existing documentation.
* Implement Default for Delay. That makes it more natural to construct the default Delay.
Please let me know what you think about this.
Are there any improvements possible?
Thanks for your help.
=> Delay: Some cleanups and documentation

src/spi.rs
=> Remove 4096 limit for SPI dma transfer size

src/reset.rs
Related issue: #382 
Explicitly set the return type of `reset::restart` as the [never type](https://doc.rust-lang.org/std/primitive.never.html).
This is already correctly set on the generated ffi bindings:
```rust
extern "C" {
#[doc = " @brief  Restart PRO and APP CPUs.\n\n This function can be called both from PRO and APP CPUs.\n After successful restart, CPU reset reason will be SW_CPU_RESET.\n Peripherals (except for WiFi, BT, UART0, SPI1, and legacy timers) are not reset.\n This function does not return."]
pub fn esp_restart() -> !;
}
```
=> feat(reset): Added restart return type

src/rmt.rs
The previous API required `rmt_item32_t` which was `Copy`, now Symbol is required which is not
=> Make Symbol Clone & Copy

src/gpio.rs
Adds gpio20 pin to esp32 target for using i2c on esp32-pico-mini-02 (such as in Adafruit ESP32 Feather V2). Fixes an issue referenced in https://github.com/esp-rs/esp-idf-hal/issues/108
=> Add GPIO20 for esp32-pico-mini-02

src/adc.rs, src/gpio.rs, src/interrupt.rs, src/rmt.rs, src/task.rs
fixes https://github.com/esp-rs/esp-idf-template/issues/193
=> add missing hysteresis filter option for esp32h2 in gpio

src/rmt.rs
https://github.com/esp-rs/esp-idf-hal/commit/5657073293b8995c11cdaf175c82d54d14dc8050 has broken the RMT driver. `Symbol(*item)` creates a copy that is never assigned to anything, making the effects of `update` useless.
Fixes #389
=> Fix FixedLengthSignal::set

src/lib.rs, src/peripherals.rs
The esp32c6 does have a pcnt unit according to the documentation that seems to be used via the same idf interface as the ones for esp32 cores. Enable it for the c6 as well. 
https://docs.espressif.com/projects/esp-idf/en/stable/esp32c6/api-reference/peripherals/pcnt.html
=> Enable pcnt for esp32c6

src/delay.rs
Ive added impls for `embedded_hal_0_2::blocking::delay::DelayMs<u8>` and `embedded_hal_0_2::blocking::delay::DelayUs<u8>` for `esp-idf-hal`'s `Delay` type since `u16` and `u32` specializations were already present, but no `u8` version.
I've noticed that some crates using `embedded_hal` version `0.2.x`, like `epd-waveshare` require the `u8` specializations of `DelayMs` or `DelayUs`, for example [here](https://docs.rs/epd-waveshare/0.5.0/src/epd_waveshare/epd7in5/mod.rs.html#99-229). Since `Ets` had the specialzation already, I added them to `Delay` as well for convenience.
=> Added DelayUs and DelayMs U8 impls for Delay

src/ledc.rs
In my project I need to drive more pins than there are ledc channels, but not at the same time
This pull request creates a way to change gpio pin on an already instantiated `LedcDriver` instance, so the channel needs only to be borrowed once
For context, the user then has to reconfigure the "orphan" gpio manually, so this is still an unsafe operation, but I guess this is outside the scope of the ledc driver, for now
let me know what you think
=> add config_with_pin method to LedcDriver

src/ledc.rs, src/peripherals.rs
To be precise, it is _not exactly the case_ that high-speed channels are not currently supported.
The problem is in _how_ they are supported: currently, there are only 8 exposed channel peripherals and 4 exposed timer peripherals.
However, the ESP32 actually has **two** groups of LEDC channels + drivers:
* High-speed group - 8 channels, 4 timers
* Low speed group - 8 channels, 4 timers (the only types all other chips have)
So in total the peripherals are: 16 channels, 8 timers. Since the two groups of channels and timers are currently overlaid over a single set of channels + timers, user has to choose - _at driver construction time_ - whether she wants to treat channel X and/or timer Y as low speed or high speed.
However, this effectively limits the total number of channels and timers …
=> (ESP32 only) Support for the high-speed channels

src/ledc.rs
The max_duty cycle is wrong, the [ESP-IDF](https://docs.espressif.com/projects/esp-idf/en/stable/esp32/api-reference/peripherals/ledc.html#change-pwm-duty-cycle-using-software) states that the duty cycle is inclusive. It is only exclusive for the maximum timer resolution. I don't have fancy electronics, but a simple test with 1 bit resolution and an LED revealed a duty cycle of 1 only led to half brightness, while a value of 2 was full brightness.
=> Fix wrong max_duty for ledc

Cargo.toml
A new version of embassy-sync has been released that supports zero initialization. I think this is a pretty important change to update
=> Update embassy-sync version to 0.6.0

CHANGELOG.md, src/spi.rs
Sometimes we only need MOSI pin of SPI peripheral, for example, for usage with WS2812 RGB led strip. This constructor adds more flexablily and keeps us from wasting pin without breaking any APIs.
Code tested on esp32-c3.
Example of usage:
https://github.com/okhsunrog/esp_pd_rs/blob/master/src/main.rs
=> Adding new_without_sclk SpiDriver constructor in SPI driver

CHANGELOG.md, src/timer.rs
Newer esp's (c2/h2/c6) don't use the apb clock as a default clock for the timer. They use different variants of the pll clock. Furthermore the general assumption that the xtal clock is always 40Mhz is not correct. This PR includes fixes for the TimeDriver in this respect.
closes #426
=> fix clock usage in timer driver for idf 5

CHANGELOG.md, src/i2c.rs
=> i2c: use correct xtal for esp32c2 on timeout calculations

.github/workflows/ci.yml, src/gpio.rs, src/timer.rs
Timer & GPIO configs are both broken for ESP IDF 4.4 and the `riscv32imac-esp-espidf` target.
=> Fix timer and gpio config for ESP IDF 4.4.x

src/adc.rs
From #446, add some docstrings for the ADC module. Mostly just add the example and some small explanation.
=> Docs: Add some docstrings for ADC module.

src/uart.rs
=> Update uart.rs, add rs485 half duplex

src/spi.rs
=> Update spi.rs, fix half3wire read

Cargo.toml, src/lib.rs, src/peripherals.rs, src/sd.rs, src/sd/mmc.rs, src/sd/spi.rs
(Related to https://github.com/esp-rs/esp-idf-svc/issues/439 and https://github.com/esp-rs/esp-idf-svc/pull/448 and supersedes https://github.com/esp-rs/esp-idf-svc/pull/448 .)
Sibling PR for `esp-idf-svc`: https://github.com/esp-rs/esp-idf-svc/pull/454
This PR introduces safe SD-Card drivers wrappers which closely follows the ESP-IDF drivers. Namely:
- High-level SD-Card driver: `SdCardDriver` which wraps a low-level SD-Card Host driver (see below) 
- Allows sector-level SD-Card access (i.e. read/write/erase sectors), as well as reads and writes with arbitrary byte lengths. 
- Currently, only the safe instantiation / drop of the driver is implemented. For sector access, one needs to use the raw `esp-idf-sys` API with the driver
- Low level SD-Card Host drivers:
- SD-SPI Host driver: …
=> SD Card driver; SD Card host drivers (SPI and SDMMC)

examples/temperature_sensor.rs, src/lib.rs, src/peripherals.rs, src/temp_sensor.rs
What the title says. Currently very much WIP. PR created to help give feedback.
Closes #333
=> Add support for ESP internal temperature sensor

src/reset.rs
The esp_reset_reason_t ESP_RST_PG and ESP_RST_CPU constant names don't seem to exist. Instead, the actual names (added in esp-idf 5.2.2) are ESP_RST_PWR_GLITCH and ESP_RST_CPU_LOCKUP.
The incorrect names caused the second-to-last match arm to be interpreted as a binding name (that is, a catch-all), causing incorrect behavior and build warnings when using esp-idf 5.2.2 and up.
---
See https://github.com/espressif/esp-idf/blame/v5.2.2/components/esp_system/include/esp_system.h#L39-L40
These were added in https://github.com/espressif/esp-idf/commit/e930ff0b1f527591b16e8f94f62ab2027b1c40fb -- I'm not sure where the incorrect names (used in #444) came from.
=> Fix esp_reset_reason_t constant names

examples/spi_loopback.rs, examples/spi_loopback_async.rs, src/spi.rs
Fixes #49
This set of commits introduces a few changes, in order to support dual and quad SPI:
* `SpiDriver::new_dual` and `SpiDriver::new_quad` constructors, to allow creating a SpiDriver while specifying additional pins and modes. 
* `LineWidth` enum
* And a `TransactionExt` struct (and functions that use it), which is an analog of the `spi_transaction_ext_t` in esp-idf.
By adding `TransactionExt`, this also enables hardware support for command, address, and dummy phases.
---
Overall, this is a little bit of a weird addition. I don't think it fits in *super* well with the existing API, but I couldn't think of a better way to do it.
In particular, some things that wouldn't work:
* Adding `LineWidth` to `Operation`, to allow using the same methods: this won't work because `Operation` …
=> Add dual and quad SPI support

src/adc.rs
In dropping AdcDriver instead of deregister event callbacks, set pointer to struct adc_continuous_evt_cbs_t to core::ptr::null(). As result, esp_idf_hal raise error:
```
E (408) adc_continuous: adc_continuous_register_event_callbacks(514): invalid argument
thread 'main' panicked at /home/ptr/.cargo/registry/src/index.crates.io-6f17d22bba15001f/esp-idf-hal-0.44.1/src/adc.rs:1330:18:
...
Rebooting...
...
```
Original documentation said "User can deregister a previously registered callback by calling this function and setting the to-be-deregistered callback member in the cbs structure to NULL".
So, deregistration must set to NULL only function pointers, not pointer to their struct.
My test code:
```
use esp_idf_hal::peripherals::Peripherals;
fn main() -> anyhow::Result<()> {
use …
```
=> Fix drop for AdcDriver in deregister event callbacks

src/task.rs
- small typo fix "fo" -> "for" in task docs
=> Typo fix in task docs

CHANGELOG.md, examples/rmt_neopixel.rs
The current `From<Rgb> for u32` implementation in NeoPixel example appears to be incorrect. 
According to the [datasheet](https://cdn-shop.adafruit.com/datasheets/WS2812.pdf), data should be sent in GRB order. This PR changes the `From<Rgb>` implementation to match the datasheet's requirement by swapping the positions of red and 
green components in the bit shifting operation.
=> Fix RGB to u32 conversion order in rmt_neopixel example

CHANGELOG.md, src/sd.rs
Fix #507 by adding the missing `sdmmc_host_get_dma_info` function pointer for the SD card host driver
The `get_dma_info` function pointer here:
https://github.com/esp-rs/esp-idf-hal/blob/8a11ef463ea78920e89755525d1cb995f13b1cec/src/sd.rs#L384-L390
supposes to be pointing to `sdmmc_host_get_dma_info` based on what I saw from the [SDMMC_HOST_DEFAULT](https://github.com/espressif/esp-idf/blob/b5ac4fbdf9e9fb320bb0a98ee4fbaa18f8566f37/components/esp_driver_sdmmc/include/driver/sdmmc_default_configs.h#L52) macro. Without this func pointer, the first time calling it will crash due to calling a null pointer from here:
https://github.com/espressif/esp-idf/blob/d7d3eb3f0a99f069a7814b3c0824626383e4a511/components/sdmmc/sdmmc_sd.c#L95
Adding patch pointing hal repo to my PR this problem is gone:
``` …
```
=> Fix #507 - add missing sdmmc_host_get_dma_info for sdcard driver

CHANGELOG.md, src/sd.rs
=> Fix #509  missing sdspi_host_get_dma_info

CHANGELOG.md, src/task.rs
The docs for task::notification::Notifier methods were outdated:
- referenced `Monitor` struct, that was renamed to `Notification`,
- referenced a `Drop` trait, that is not implemented anymore,
- described implementation details that are no longer accurate.
N/A
=> fix: update docs for task::notification::Notifier

CHANGELOG.md, examples/adc.rs, examples/adc_oneshot.rs, src/adc.rs
ESP-IDF 5 deprecated `ADC_ATTEN_DB_11` and introduced `ADC_ATTEN_DB_12`, I think we should reflect that.
-
=> feat: add `DB_12` adc attenuation and deprecate `DB_11` for ESP-IDF V5.0+

CHANGELOG.md, examples/ledc_threads.rs
This pull request replaces the use of `Arc` with `Rc` for sharing the `LedcTimerDriver` instance among multiple `LedcDriver` instances in the `ledc_threads` example. This change addresses a clippy warning (usage of an `Arc` that is not `Send` and `Sync`).
The updated code compiles without issues and runs successfully on a device.
=> Replace Arc with Rc in ledc_threads example

CHANGELOG.md, examples/pcnt_rotary_encoder.rs
Update pcnt_rotary_encoder example to use gpio4 instead of gpio6 because gpio6 is connected to the integrated SPI flash (SCK/CLK) and causes `PcntDriver::channel_config()` to hang when used on the base esp32 on which it was tested.
=> Pcnt example

CHANGELOG.md, examples/ledc_fade.rs, src/ledc.rs
Added `fade_stop` for `LedcDriver`. This method can be used if fade is started by `fade_with_*` and `wait: false`. Otherwise `set_duty` will be block the thread until target duty is reached.
Following #519
I added new code to ledc_fade.rs example, which shows how to use the new functionality. I have run this successfully on an esp32-s3 SoC with an external led.
=> ledc: add fade stop

CHANGELOG.md, Cargo.toml, src/can.rs
=> fix wrong Alert enum indexing

CHANGELOG.md, src/uart.rs
This pull request allows for sending  a UART break condition after a write. Ideally, I'd want to just send a break condition, but that functionality is not exposed by esp-idf. This at least allows for parity with esp-idf.
I've manually tested the PR. I'm using this fork in a project that has a UART connection between a ESP32-C6 and an RP2350. Writing with a break triggers the break detection in the RP2350, regular writes don't.
=> Support for sending UART break conditions

CHANGELOG.md, src/gpio.rs
Provides an unsafe escape hatch that prevents the HAL GPIO driver from initializing the ISR service a second time.
Not yet tested, but I will do on-device tests this weekend.
=> Provide an escape hatch for esp-rs/esp-idf-hal#537
