esp-rs/esp-idf-hal

src/delay.rs, src/gpio.rs, src/i2c.rs, src/lib.rs, src/peripherals.rs, src/serial.rs, src/spi.rs
Format repo according to current default Rustfmt settings
=> Run cargo +nightly fmt over the repo

src/serial.rs
Fixes https://github.com/esp-rs/esp-idf-hal/issues/5
=> Fix serial driver

src/gpio.rs
In a similar fashion to https://github.com/esp-rs/esp-idf-sys/pull/26.
=> cfg gate dac for esp32s3

src/gpio.rs
While #16 added the ability to downgrade a pin from a concrete type to a more generic one (ie. `GpioPin`), it did _not_ implement the various `embedded-hal` traits for this type. This PR implements said traits.
With this PR, you're now able to loop/iterate over a collection of `GpioPins` and set/read their state. For example:
```rust
let gpio0 = pins.gpio0.into_input()?.degrade();
let gpio1 = pins.gpio1.into_input()?.degrade();
let gpio2 = pins.gpio2.into_input()?.degrade();
let pins_vec = vec![gpio0, gpio1, gpio2];
let pin_states = &pins_vec
.iter()
.map(|pin| pin.is_high().unwrap())
.collect::<Vec<_>>();
```
=> Implement embedded-hal traits for downgraded GPIOs

README.md, examples/blinky.rs, examples/button.rs, examples/i2c_ssd1306.rs, examples/spi_loopback.rs, examples/uart_loopback.rs
This adds a couple of basic examples showing
- basic GPIO
- SPI
- UART
- I2C
=> Add more basic examples

src/can.rs
nb::block! macro functions as expected for receive and transmit per example on ESP32-C3 rev 3! 
Thanks @andresv @ivmarkov!
=> Enable nb api for CAN (TWAI) (embedded-hal 0.2.7)

src/serial.rs
Currently it's only possible to write bytes individually, i.e. with some time between each byte.
This PR allows to write from and read into a slice with a single call to the IDF API so that bytes while be transferred in one go instead of having to call it for every byte.
=> serial: Add {read,write}_bytes

src/rmt.rs
From [Issue #89](https://github.com/esp-rs/esp-idf-hal/issues/89)
=> Added `with_capacity()` to VariableLengthSignal

src/lib.rs
=> Fix typo in doc copy

src/adc.rs, src/delay.rs, src/gpio.rs, src/i2c.rs, src/interrupt.rs, src/rmt.rs, src/task.rs, src/timer.rs, src/uart.rs
- Requires esp-rs/esp-idf-sys#157
=> Adjust for `esp-idf-sys` size_t -> usize

examples/ledc-simple.rs, examples/ledc-threads.rs, src/ledc.rs
=> #180 ledcdriver redundand timer config

src/spi.rs
Thank you so much for maintaining this repository!
Here is a minor typo fix.
=> Fix a typo

.github/workflows/ci-esp-idf-master.yml, .github/workflows/ci.yml, .github/workflows/publish-dry-run.yml, .github/workflows/publish.yml
- Remove `actions-rs` actions
- Format CI files the same way
- Remove unnecessary dependency
- Upgrade checkout action version
=> Improve CI

src/uart.rs
Just a tiny detail that needed fixing after serial -> uart refactoring
=> Fix UART docs

README.md
Hi
Trying a relatively simple change here to test out contributing to this repo. 
As mentioned in https://github.com/esp-rs/esp-idf-hal/issues/270 I had some issues building the repo, so I wanted to update the README.md to make it abit easier.
Also related to https://github.com/esp-rs/esp-idf-hal/issues/240
Thanks to @Vollbrecht for helping out with how the espflash commands work for different versions.
=> Update instructions for building examples

CHANGELOG.md, src/i2c.rs, src/interrupt.rs, src/spi.rs, src/task.rs
=> 🗑️ add deprecate note on 4.3 specific cfg

src/i2s.rs
I had to modify the code from the doc to build an example application.
This is an update for that.
When is the next release scheduled? 
I am so exited for the i2s support!
=> doc: i2s example usage update

examples/i2c_master_slave.rs
=> Fixed one character typo.

src/can.rs
In my project, I'm using `Mode::NoAck` to self-test the CAN controller (loopback of transmissions) and self-reception frame.
This pull request adds a missing [self-reception frame](https://docs.espressif.com/projects/esp-idf/en/stable/esp32s3/api-reference/peripherals/twai.html#message-fields-and-flags).
=> Add CAN Frame flags

src/i2c.rs
Use the newer calculation for the i2c
=> Fix for #412

src/i2s.rs
Small improvement for bidirectional I2S, as sometimes it is necessary to read and write to a channel from different tasks/threads
=> Allow split bidirectional I2S

src/delay.rs, src/rmt.rs
From https://github.com/esp-rs/esp-idf-hal/actions/runs/11044155929/job/30679619215
=> Fix some clippy lints

CHANGELOG.md, src/ledc.rs
`LedcTimerDriver` returns a `Result` while `get_max_duty` doesn't.
Describe how you tested your changes.
=> Fix ledc example

CHANGELOG.md, src/can.rs
`AsyncCanDriver` is now `Send`
=> `Send` AsyncCanDriver

.github/workflows/ci-esp-idf-next.yml, .github/workflows/ci.yml
Bumps xtensa-toolchain to latest release.
CI
=> Update xtensa-toolchain version
